FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install torch torchvision torchaudio \
    --index-url https://download.pytorch.org/whl/cu118

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 빌드 이후 모델을 설치하면 상당히 오래걸림. 빌드할때 설치해버리기
ARG MODEL_NAME=torchtorchkimtorch/Llama-3.2-Korean-GGACHI-1B-Instruct-v1
RUN python - <<EOF
from transformers import AutoTokenizer, AutoModelForCausalLM
AutoTokenizer.from_pretrained("$MODEL_NAME")
AutoModelForCausalLM.from_pretrained("$MODEL_NAME")
EOF

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
